### ISSUE TITLE
Suggestion: Throw an error when node-fetch returns something other than 200 OK

### ISSUE THREAD

**Issue by dougludlow** [ng-apimock/base-client#1]
I've been debugging an issue for a few hours now, where, when I was calling selectScenario, nothing was happening.  I ended up throwing console.logs all throughout the `@ng-apimock/*` packages to try figure out what was going on. Eventually I discovered that the ng-apimock core api wasn't being hit at all and I ultimately found out that I needed to add an entry in my `proxy.config.json` for "ngapimock". It would have helped if fetch threw an error when a non 200 status code is returned, then I would have found out a lot earlier on why selectScenario wasn't working.

**Comment by mdasberg** [comment]
hi @dougludlow, good suggestion, I will add it asap

**Comment by dougludlow** [comment]
I can create a PR for it as well, if that would be helpful?

**Comment by mdasberg** [comment]
@dougludlow I just release v1.0.12 and am currently updating the clients.
