### ISSUE TITLE
3 high severity vulnerabilities, possible fix?

### ISSUE THREAD

**Issue by ringodotnl** [ng-apimock/base-client#713]
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
No fix available
node_modules/@ng-apimock/base-client/node_modules/node-fetch
  @ng-apimock/base-client  <=3.1.0
  Depends on vulnerable versions of node-fetch
  node_modules/@ng-apimock/base-client
    @ng-apimock/cypress-plugin  *
    Depends on vulnerable versions of @ng-apimock/base-client
    node_modules/@ng-apimock/cypress-plugin

**Comment by mdasberg** [comment]
Let me try create a pr

**Comment by mdasberg** [comment]
@ringodotnl v3.3.1 has been released with the latest v2 version which resolves the security issue. Thanks for reporting it.
